packages:
  - packages/*

catalog:
  '@biomejs/biome': 1.9.4
  '@chromatic-com/storybook': 4.1.3
  '@egoist/tailwindcss-icons': 1.9.0
  '@iconify-json/heroicons': 1.2.3
  '@storybook/addon-a11y': 10.0.8
  '@storybook/addon-docs': 10.0.8
  '@storybook/addon-vitest': 10.0.8
  '@storybook/react': 10.0.8
  '@storybook/react-vite': 10.0.8
  '@types/js-yaml': 4.0.9
  '@types/node': 22.19.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@types/xml2js': 0.4.14
  '@vitest/browser-playwright': 4.0.13
  '@vitest/coverage-v8': 4.0.13
  autoprefixer: 10.4.22
  classnames: 2.5.1
  date-fns: 4.1.0
  feed: 4.2.2
  gray-matter: 4.0.3
  js-yaml: 4.1.1
  orval: 7.17.0
  playwright: 1.56.1
  postcss: 8.5.6
  react: 19.2.0
  react-dom: 19.2.0
  react-markdown: 9.1.0
  storybook: 10.0.8
  tailwindcss: 4.1.17
  tsup: 8.5.1
  tsx: 4.20.6
  turbo: 2.6.1
  typescript: 5.9.3
  vitest: 4.0.13
  xml2js: 0.6.2
  zod: 3.25.76

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
